using System.Diagnostics;
using System.Globalization;
using System.Text.Json;
using System.Windows;
using Microsoft.Win32;
using Forms = System.Windows.Forms;

namespace AutoCutStudio.Rebuild;

public sealed partial class MainWindow
{
    private async void NewProject(object? sender, RoutedEventArgs e) { using var dialog = new Forms.FolderBrowserDialog { Description = "เลือกโฟลเดอร์แม่ของโปรเจกต์" }; if (dialog.ShowDialog() != Forms.DialogResult.OK) return; var name = "AutoCut Rebuild " + DateTime.Now.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture); _project = new ProjectDocument { DisplayName = name, RootPath = Path.Combine(dialog.SelectedPath, name) }; await ProjectStore.SaveAsync(_project); Refresh("สร้างโปรเจกต์แล้ว"); }
    private async void OpenProject(object? sender, RoutedEventArgs e) { var dialog = new OpenFileDialog { Filter = "AutoCut Project|project.json|JSON|*.json" }; if (dialog.ShowDialog(this) != true) return; _project = await ProjectStore.LoadAsync(dialog.FileName); Refresh("เปิดโปรเจกต์แล้ว"); }
    private async void SaveProject(object? sender, RoutedEventArgs e) { if (_project is null) return; await ProjectStore.SaveAsync(_project); Refresh("บันทึกแล้ว"); }
    private async void Import(object? sender, RoutedEventArgs e) { if (!RequireProject()) return; var dialog = new OpenFileDialog { Filter = "Video|*.mp4;*.mov;*.mkv;*.avi;*.webm|All files|*.*", Multiselect = true }; if (dialog.ShowDialog(this) != true) return; foreach (var path in dialog.FileNames) { _status.Text = "กำลังตรวจ " + Path.GetFileName(path); var item = new MediaAsset { SourcePath = Path.GetFullPath(path), DisplayName = Path.GetFileName(path), Sha256 = await Security.Sha256Async(path), Probe = await _probe.ProbeAsync(path) }; _project!.Media.Add(item); _editor.Add(_project, item); } await ProjectStore.SaveAsync(_project!); Refresh("นำเข้าสื่อแล้ว"); }
    private void ShowSystemDoctor(object? sender, RoutedEventArgs e) { var window = new SystemDoctorWindow(_project?.RootPath) { Owner = this }; window.ShowDialog(); }
    private async void Export(object? sender, RoutedEventArgs e) { if (!RequireProject()) return; var job = new JobDocument { Kind = JobKind.ExportTimeline, State = JobState.Queued, ProjectRoot = _project!.RootPath, OutputPath = VersionedOutput.Next(Path.Combine(_project.RootPath, "exports"), "output", ".mp4"), Clips = _project.Timeline.OrderBy(x => x.Order).Where(x => x.Enabled).Select(x => { var media = _project.Media.Single(m => m.MediaId == x.MediaId); return new ClipInput { SourcePath = media.SourcePath, SourceInSeconds = x.SourceInSeconds, SourceOutSeconds = x.SourceOutSeconds }; }).ToList() }; await RunJob(job); }
    private async void Trim(object? sender, RoutedEventArgs e) { if (_project is null || _timeline.SelectedItem is not TimelineRow row || !double.TryParse(_input.Text, NumberStyles.Any, CultureInfo.InvariantCulture, out var input) || !double.TryParse(_output.Text, NumberStyles.Any, CultureInfo.InvariantCulture, out var output)) return; _editor.Trim(_project, row.ClipId, input, output); await ProjectStore.SaveAsync(_project); Refresh("Trim แล้ว"); }
    private async void Split(object? sender, RoutedEventArgs e) { if (_project is null || _timeline.SelectedItem is not TimelineRow row || !double.TryParse(_output.Text, NumberStyles.Any, CultureInfo.InvariantCulture, out var time)) return; _editor.Split(_project, row.ClipId, time); await ProjectStore.SaveAsync(_project); Refresh("Split แล้ว"); }
    private async void Delete(object? sender, RoutedEventArgs e) { if (_project is null || _timeline.SelectedItem is not TimelineRow row) return; _editor.Delete(_project, row.ClipId); await ProjectStore.SaveAsync(_project); Refresh("ลบจาก Timeline แล้ว"); }
    private async Task Move(int delta) { if (_project is null || _timeline.SelectedItem is not TimelineRow row) return; _editor.Move(_project, row.ClipId, row.Order + delta); await ProjectStore.SaveAsync(_project); Refresh("จัดลำดับแล้ว"); }
    private async Task RunSelected(JobKind kind, string extension) { if (!Selected(out var media)) return; await RunJob(NewInputJob(kind, media!, extension)); }
    private async void Transcribe(object? sender, RoutedEventArgs e) { if (!Selected(out var media)) return; var dialog = new OpenFileDialog { Filter = "Whisper model|*.bin" }; if (dialog.ShowDialog(this) != true) return; var job = NewInputJob(JobKind.Transcribe, media!, ".srt"); job.WhisperModelPath = dialog.FileName; await RunJob(job); }
    private async void BurnSubtitle(object? sender, RoutedEventArgs e) { if (!Selected(out var media)) return; var dialog = new OpenFileDialog { Filter = "Subtitle|*.srt;*.ass;*.vtt" }; if (dialog.ShowDialog(this) != true) return; var job = NewInputJob(JobKind.BurnSubtitle, media!, ".mp4"); job.SubtitlePath = dialog.FileName; await RunJob(job); }
    private async void MixVoiceover(object? sender, RoutedEventArgs e) { if (!Selected(out var media)) return; var dialog = new OpenFileDialog { Filter = "Voiceover|*.wav;*.mp3;*.m4a" }; if (dialog.ShowDialog(this) != true) return; var job = NewInputJob(JobKind.MixVoiceover, media!, ".mp4"); job.VoiceoverPath = dialog.FileName; await RunJob(job); }
    private async void OverlayLogo(object? sender, RoutedEventArgs e) { if (!Selected(out var media)) return; var dialog = new OpenFileDialog { Filter = "Logo|*.png;*.jpg;*.webp" }; if (dialog.ShowDialog(this) != true) return; var job = NewInputJob(JobKind.OverlayLogo, media!, ".mp4"); job.LogoPath = dialog.FileName; await RunJob(job); }
    private JobDocument NewInputJob(JobKind kind, MediaAsset media, string extension) => new() { Kind = kind, State = JobState.Queued, ProjectRoot = _project!.RootPath, InputPath = media.SourcePath, OutputPath = VersionedOutput.Next(Path.Combine(_project.RootPath, "exports"), kind.ToString().ToLowerInvariant(), extension) };
}
