<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>AutoCutStudio.Worker</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoCutStudio.Core\AutoCutStudio.Core.csproj" />
    <ProjectReference Include="..\AutoCutStudio.Infrastructure\AutoCutStudio.Infrastructure.csproj" />
  </ItemGroup>
</Project>
